<?php
$_helper = Mage::helper('ricardomartins_pagseguro');
?>
<input type="hidden" name="payment[sender_hash]" id="admin_sender_hash"/>
<script type="text/javascript">
    //<![CDATA[
    PagSeguroDirectPayment.setSessionId('<?php echo $_helper->getSessionId();?>');
    var iid = setInterval(function()
    {
        if(typeof PagSeguroDirectPayment != "undefined" && PagSeguroDirectPayment.ready){
            console.log('PagSeguro ready');

            clearInterval(iid);
            RMPagSeguro.updateSenderHash();
        }
    }, 4000);
    document.getElementById('edit_form').appendChild(document.getElementById('admin_sender_hash'));
    //]]>
</script>