<div id="pagseguro-mask" style="display:none;">
    <p class="loader" id="pagseguro_mask_loader">
        <img src="<?php echo $this->getSkinUrl('images/ricardomartins_pagseguro/loader.gif') ?>"
             alt="<?php echo Mage::helper('core')->__('Loading...') ?>" />
            <br />
            <?php echo Mage::helper('core')->__('Please wait...') ?>
    </p>
</div>

<div id="pagseguro-overlay" style="display:none;"></div>

